#!/bin/bash

set -e

cli_directory=$(dirname $0)/.venv/invenio-cli

test -d $cli_directory || {
  echo "Invenio client not found, see the webpage for tutorial on initializing OA Repository"
  exit 1
}

$cli_directory/bin/invenio-cli $@