version: "2.2"
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
    ports:
      - "${INVENIO_REDIS_HOST}:${INVENIO_REDIS_PORT}:6379"
  db:
    extends:
      file: docker-services.yml
      service: db
    ports:
      - "${INVENIO_DATABASE_HOST}:${INVENIO_DATABASE_PORT}:5432"
  mq:
    extends:
      file: docker-services.yml
      service: mq
    ports:
      - "${INVENIO_RABBIT_HOST}:${INVENIO_RABBIT_ADMIN_PORT}:15672"
      - "${INVENIO_RABBIT_HOST}:${INVENIO_RABBIT_PORT}:5672"
  search:
    extends:
      file: docker-services.yml
      service: search
    ports:
      - "${INVENIO_OPENSEARCH_HOST}:${INVENIO_OPENSEARCH_PORT}:9200"
      - "${INVENIO_OPENSEARCH_HOST}:${INVENIO_OPENSEARCH_CLUSTER_PORT}:9600"
{%- if cookiecutter.development_tools == "yes"%}
  opensearch-dashboards:
    extends:
      file: docker-services.yml
      service: opensearch-dashboards
    ports:
      - "${INVENIO_OPENSEARCH_DASHBOARD_HOST}:${INVENIO_OPENSEARCH_DASHBOARD_PORT}:5601"
    expose:
      - "5601"
  pgadmin:
    extends:
      file: docker-services.yml
      service: pgadmin
{%- endif %}

  s3:
    extends:
      file: docker-services.yml
      service: s3
    ports:
      - "${INVENIO_S3_HOST}:${INVENIO_S3_PORT}:9000"
      - "${INVENIO_S3_HOST}:${INVENIO_S3_PORT1}:9001"
volumes:
  data:
