from oarepo_cli.model.utils import ModelWizardStep
from oarepo_cli.utils import get_cookiecutter_source
from oarepo_cli.wizard import InputStep, RadioStep, StaticStep, Wizard, WizardStep


class CreateModelWizardStep(ModelWizardStep, WizardStep):
    def after_run(self):
        model_dir = self.model_dir
        base_model_package = {
            "empty": "(none)",
            "common": "nr-common-metadata-model-builder",
            "documents": "nr-documents-records-model-builder",
            "data": "TODO",
        }.get(self.data["model_kind"])
        base_model_use = base_model_package.replace("-model-builder", "")

        cookiecutter_path, cookiecutter_branch = get_cookiecutter_source(
            "OAREPO_MODEL_COOKIECUTTER_VERSION",
            "https://github.com/oarepo/cookiecutter-model",
            "v11.0",
            master_version="master",
        )

        self.run_cookiecutter(
            template=cookiecutter_path,
            config_file=f"model-{model_dir.name}",
            checkout=cookiecutter_branch,
            output_dir=str(model_dir.parent),
            extra_context={
                **self.data,
                "model_name": model_dir.name,
                "base_model_package": base_model_package,
                "base_model_use": base_model_use,
            },
        )
        self.data["model_dir"] = str(model_dir.relative_to(self.data.project_dir))

    def should_run(self):
        return not self.model_dir.exists()


add_model_wizard = Wizard(
    StaticStep(
        heading="""
Before creating the datamodel, I'll ask you a few questions.
If unsure, use the default value.
    """,
    ),
    RadioStep(
        "model_kind",
        heading="""
Now choose if you want to start from a completely empty model or if you
want to base your model on an already existing one. You have the following
options:

* common       - a common set of metadata created by the National library of Technology, Prague
                 compatible with Dublin Core
                 See https://github.com/Narodni-repozitar/nr-common-metadata for details
* documents    - extension of common, can be used to capture metadata of documents (articles etc.)
                 See https://github.com/Narodni-repozitar/nr-documents-records for details
* data         - extension of common for capturing generic metadata about datasets
                 See TODO for details
* custom_model - use any custom model as a base model. If you select this option, answer the next two questions
                 (base_model_package, base_model_use) as well
* empty_model  - just what it says, not recommended as you have no compatibility with
                 the Czech National Repository

When asked about the base_model_package: leave as is unless you have chosen a custom base model.
In that case enter the package name of the model builder extension on pypi which contains the custom model.

When asked about the base_model_use: leave as is unless you have chosen a custom base model.
In that case enter the string that should be put to 'oarepo:use. Normally that is the name
of the extension without 'model-builder-'. See the documentation of your custom model for details.
    """,
        options={
            "common": "Common set of metadata, DC compatible",
            "documents": "Based on Czech National Repository documents metadata",
            "data": "Based on Czech National Repository datasets metadata",
            "empty": "Just use empty model, I'll add the metadata myself",
        },
        default="common",
    ),
    StaticStep(
        heading="""
Now tell me something about you. The defaults are taken from the monorepo, feel free to use them.
    """,
    ),
    InputStep(
        "author_name",
        prompt="""Model author""",
        default=lambda data: (get_site(data) or {}).get("author_name"),
    ),
    InputStep(
        "author_email",
        prompt="""Model author's email""",
        default=lambda data: (get_site(data) or {}).get("author_email"),
    ),
    RadioStep(
        "permissions_presets",
        heading="Would you like to set up permissions",
        options={
            "no": "no",
            "read_only": "read only access to records, no one can create or edit them",
            "everyone": "every user (both authenticated or anonymous) can create, edit and delete any record",
        },
        default="yes",
    ),
    InputStep(
        "pid_type",
        prompt="""Specify the name of the type of the pid of the model. If nothing is provided,
         it will be autogenerated.""",
        default="",
        required=False,
    ),
    RadioStep(
        "use_drafts",
        heading="Should records be first uploaded as editable drafts before they are published?",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="yes",
    ),
    StaticStep(
        heading="Now you can choose which plugins you need in the repo.", pause=True
    ),
    RadioStep(
        "use_files",
        heading="Will you upload files to the records in this model? If the repository is not metadata only, answer yes.",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="yes",
    ),
    RadioStep(
        "use_requests",
        heading="Do you need approval process for the records in this model? We recommend to use it, otherwise your changes would be immediately visible.",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="yes",
    ),
    RadioStep(
        "use_expandable_fields",
        heading="Will you use expandable fields? If in doubt, choose no.",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="no",
    ),
    RadioStep(
        "use_relations",
        heading="Will you use relations to different records? For example, if this model represents a Dataset, relation to Article model.",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="yes",
    ),
    RadioStep(
        "use_custom_fields",
        heading="Would you like to make your model extensible during deployment via custom fields?",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="yes",
    ),
    RadioStep(
        "use_vocabularies",
        heading="Will you use vocabularies in your model?",
        options={
            "yes": "yes",
            "no": "no",
        },
        default="yes",
    ),
    StaticStep(
        heading="Now I have all the information to generate your model. After pressing Enter, I will generate the sources",
        pause=True,
    ),
    CreateModelWizardStep(),
    StaticStep(
        heading=lambda data: f"""
The model has been generated in the {data.section} directory.
At first, edit the metadata.yaml and then run "nrp-cli model compile {data.section}"
and to install to the site run "nrp-cli model install {data.section}".
                     """,
        pause=True,
    ),
)


def get_site(data):
    primary_site_name = data.get("config.primary_site_name")
    return data.get(f"sites.{primary_site_name}")
