NRP_CLI_VERSION = "oarepo-cli>=11.0.8,<12"
SITE_COOKIECUTTER_REPO = "https://github.com/oarepo/cookiecutter-site"
SITE_COOKIECUTTER_VERSION = "v11-nopipfile"
OAREPO_VERSION = "oarepo>=11,<12"
PYTHON_VERSION = ">=3.9,<=3.10"
